### ISSUE TITLE
Multiple enhanced fanout issue

### ISSUE THREAD

**Issue by jachen-alch** [lifion/lifion-kinesis#153]
Hello,
We are seeing an issue while running the lifion-kinesis consumer with enhanced fanout enabled. We are unable to get multiple processes to consume from the same shard. When enhanced fanout is disabled, this works correctly, but with fanout enabled, only one of the processes is able to consume events from our shard. Here is some info on our setup:

lifion version: 1.0.8
Node.js version: 10.15.3
number of consumers: 2
number of shards: 1

Here is how we initialize our consumer: 
```
const headerKinesis = new Kinesis({
    streamName: HEADERS_STREAM,
    consumerGroup: instanceId + "_" + pid,
    dynamoDb: {
      region: "us-east-1",
    },
    region: "us-east-1",
    logger,
  });
```
The goal is to have each consumer receive every event from the single shard, which is why we set a unique `consumerGroup` for each consumer.

When running, we see the same fan-out consumer in the logs of both consumers:
`Using the "lifion-kinesis-e8xKvnt2XXDmRkDjp53quz" enhanced fan-out consumer.`
but only one of the processes is able to receive events from this shard. 

Is there a reason we are unable to receive the same kinesis events in all the processes? Is there an issue with our configuration? Any help or insight would be greatly appreciated! Let me know if any additional information would be helpful as well.

Thanks,
James

**Comment by eaviles** [comment]
@jachen-alch the problem is that a registered enhanced fan-out consumer in AWS can only be used in one active subscription to a shard. This means the consumer "lifion-kinesis-e8xKvnt2XXDmRkDjp53quz" cannot be used at the same time by 2 processes.

Right now, the sate of which process is using which enhanced consumer is kept by consumer group. If you use 2 different consumer groups in the 2 processes both will think the same enhanced consumer is not in use and will try to use it.

If what you want to do is to have both processes reading from the same shard, you could:
1. Use the same consumer group in both processes.
2. Instantiate the client with the `useAutoShardAssignment` set to `false` and of course `useEnhancedFanOut` set to `true`.

This way both processes will use a different enhanced fan-out consumer but will read from the same shard and will get the same messages.

Let me know if this works out for you.

**Comment by jachen-alch** [comment]
@eaviles thanks for the reply! I tried out your suggestions:
-Same consumer group name
-`useAutoShardAssignment` set to `false` and `useEnhancedFanOut` set to `true`

It worked initially on our two consumers. However, after ~20 minutes of running, one of the consumers will get this error:

```
[2019-06-14T21:22:42+0000] [ERROR]  Subscription unsuccessful: 500
[2019-06-14T21:22:42+0000] [WARN]   Trying to recover from AWS.Kinesis error…
	- Message: Failed to subscribe to shard.
	- Request ID: undefined
	- Code: InternalFailure (500)
	- Stream: test.stream
[2019-06-14T21:22:42+0000] [WARN]   Waiting before retrying the pipeline…
[2019-06-14T21:22:51+0000] [ERROR]  Subscription unsuccessful: 400
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Another active subscription exists for this consumer: 209202477790:staging.eth.kovan.blocks:shardId-000000000000:lifion-kinesis-pGqfPtsXrbwK89kjuzaV3d
    at PreProcess._transform (/var/app/current/vendor/lifion-kinesis/lib/fan-out-consumer.js:82:9)
    at PreProcess.Transform._read (_stream_transform.js:190:10)
    at PreProcess.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at PreProcess.Writable.write (_stream_writable.js:294:11)
    at DuplexWrapper.ondata (_stream_readable.js:689:20)
    at DuplexWrapper.emit (events.js:189:13)
    at DuplexWrapper.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
```

I saw this happen separately on two different tests. It does continue to log `Using the "lifion-kinesis-pGqfPtsXrbwK89kjuzaV3d" enhanced fan-out consumer.` but no longer receives data from the stream. Do you have any idea what is causing this bug, how to prevent it, or make the code resilient to this failure so it continues to receive data from the stream?

Thanks,
James

**Comment by eaviles** [comment]
@jachen-alch the module should auto-retry to create the stream pipeline on any 400 or 500 errors so in the scenario above the module should re-connect by itself. I'll try to replicate this problem myself. Is it very consistent for you? like as in, happens every time after 20 mins or so?

**Comment by jachen-alch** [comment]
Thanks @eaviles . I've tested it twice and it happened both times. The first after ~30 min, the second after ~20 min. I'll run it a few more times on my side as well.

**Comment by jachen-alch** [comment]
Hey @eaviles , I ran a long running test with a few consumers. They all seem to eventually succumb to the same error, but at different times i.e. time to failure is not deterministic. What's interesting is that after the failure I still see these log messages:
```
[2019-06-21T18:44:42+0000] [DEBUG]  Using the "lifion-kinesis-pGqfPtsXrbwK89kjuzaV3d" enhanced fan-out consumer.
[2019-06-21T18:44:42+0000] [DEBUG]  Retrieving shards for the "testing.stream" stream…
```
but I no longer see `Subscription to shard is successful`

I've also added logging statements into the `.on('data' ...` callback and those log statements stop showing up after the failure. 

Looking into the consumer state in dynamo, the consumer's heartbeat is still being updated as well.

Somehow the subscription to the shard is unsuccessful after the failure? Any ideas?

Thanks,
James

**Comment by jachen-alch** [comment]
Hi @eaviles , any update on this?

Thanks,
James

**Comment by chendoron** [comment]
@jachen-alch, sorry for the delay, we're still looking into this :)

**Comment by eaviles** [comment]
@jachen-alch sorry for the delay! we found and corrected the issue. We will merge and release the PR linked here soon.
