### ISSUE TITLE
JSON Parsing should be optional

### ISSUE THREAD

**Issue by just-create** [lifion/lifion-kinesis#241]
Parsing JSON as part of the consumer should not be part of the responsibility of the consumer. First of all, it tries to parse JSON if it looks like it might maybe possibly have JSON. If that rough assumption is wrong, it throws a parser error which is not expected from a user of the library perspective. There are multiple errors that can occur (syntax errors, out of memory) that a consumer user might want to deal with specifically. The consumer user might also want to use more optimized JSON parsers if they know the schema.

I would like to suggest that either the consumer code should NOT parse the JSON automatically or that it should be optional.

https://github.com/lifion/lifion-kinesis/blob/0ae854fb335275fcdec93746453dd3cd480110c9/lib/records.js#L85

**Comment by ad34** [comment]
IS_JSON_REGEX matchs your data , even if it s not json ?

**Comment by jennyEckstein** [comment]
@just-create Thank you for bringing this issue to our attention. We have released version 1.1.3 that makes it optional to parse your data.
