### ISSUE TITLE
ConditionalCheckFailedException

### ISSUE THREAD

**Issue by carlo-quinonez** [lifion/lifion-kinesis#274]
The library seems to be working just fine, but the `stats` indicate that DynamoDB is running into exceptions (about 1 every ~10 seconds). The exception is non-specific and the logs didn't show any errors either.

```
        {
          message: 'The conditional request failed',
          timestamp: 2019-12-18T20:20:14.937Z,
          code: 'ConditionalCheckFailedException',
          requestId: '5VT6DOA0TTOSJ1NC7T5PQ27HDBVV4KQNSO5AEMVJF66Q9ASUAAJG',
          statusCode: 400
        }
```

Are these exceptions expected?

**Comment by eaviles** [comment]
Hi @carlo-quinonez, yes those are expected. They are conditional updates to prevent concurrent override of locked data. An example of this is, 2 consumers trying to lease the same shard. They both try to do a conditional update, only of the 2 requests is successful. These are safe to ignore.

**Comment by eaviles** [comment]
@carlo-quinonez closing this. We can re-open it if you want to follow up.

**Comment by carlo-quinonez** [comment]
@eaviles No need to reopen. It's working just fine and if those are expected exceptions, there's no need to fix anything. That said, would there be a way to handle those exceptions inside the library so they don't bubble up to the client? I could submit a PR if you want to point me in the right direction.

**Comment by eaviles** [comment]
That would be great!

**Comment by dselman** [comment]
> @eaviles No need to reopen. It's working just fine and if those are expected exceptions, there's no need to fix anything. That said, would there be a way to handle those exceptions inside the library so they don't bubble up to the client? I could submit a PR if you want to point me in the right direction.

Did a PR get merged to address this?

**Comment by carlo-quinonez** [comment]
I never looked into this problem.
