### ISSUE TITLE
Not able to call continuePolling

### ISSUE THREAD

**Issue by yogeshwaran-manoharan** [lifion/lifion-kinesis#277]
Hi

We've been using your library and it works awesome. But not able to use [options.usePausedPolling].

I've set usePausedPolling to be `true`, but I am not able to call `continuePolling()` function on lifion-kinesis object. Can you please check it? 

Thanks in Advance :)

**Comment by eaviles** [comment]
Hi @yogeshwaran-manoharan , after setting `usePausedPolling=true` you’ll get the `continuePolling()` function from the object you get when listening for data: `client.on(‘data’, ({ records, continuePolling }) => { … })`

**Comment by eaviles** [comment]
Hi @yogeshwaran-manoharan let me know if the above was useful or not (so I can close this issue). I'll follow up with a note in the README file about this.

**Comment by eaviles** [comment]
Hi @yogeshwaran-manoharan, closing this for now. We can re-open it if you want to follow up.
