### ISSUE TITLE
Not able to call setCheckpoint()

### ISSUE THREAD

**Issue by duinness** [lifion/lifion-kinesis#298]
When setting [useAutoCheckpoints] to false I can see that checkpoints stop being set, but I do not see where/how I should use setCheckpoint() to store the sequence number for a shard.
The setCheckpoint() function doesn't appear to be available outside of the lifion-kinesis library.

I'll start working on a PR for this, but I wanted to check and see if maybe there was something I was missing.

Thanks!

**Comment by eaviles** [comment]
Hi @duinness, after setting `useAutoCheckpoints=false` you’ll get the `setCheckpoint(seqNum)` from the object you get when listening for data: `client.on(‘data’, ({ records, setAutoCheckpoint }) => { … })`

**Comment by eaviles** [comment]
HI @duinness let me know if the above resolves this issue (so I can close it). I'll make sure to put a clarification in the README.

**Comment by duinness** [comment]
@eaviles, this resolves my issue.

Thank you for the quick response! 🥇

**Comment by duinness** [comment]
Also, I assume you meant "setCheckpoint" rather than "setAutoCheckpoint" 🙂

**Comment by eaviles** [comment]
> Also, I assume you meant "setCheckpoint" rather than "setAutoCheckpoint" 🙂

🙈 yes, that's correct.

Let me know how it goes @duinness! Interested to hear feedback from external users of this module.
