### ISSUE TITLE
DescribeStream rate limit

### ISSUE THREAD

**Issue by jachen-alch** [lifion/lifion-kinesis#312]
Hello!
We started using this library with a base case in our system and since it worked so well we scaled it out with multiple consumers. However, we started seeing "LimitExceededExceptions" being returned from AWS and after investigating, we were hitting the `DescribeStream` request rate limit of 10 qps **per account**. Looking into the code we see that it's being called by `checkIfStreamExists` [here](https://github.com/lifion/lifion-kinesis/blob/6f3197fd97ccb3b7284994ea5239e5f31108086e/lib/lease-manager.js#L207) every 20 seconds. 

This seems to put a hard cap on the number of consumers we can spin up with lifion. Has anyone else reported running into this rate limit before? Are there ways to get this stream data other than from DescribeStream?

Thank you!
James

**Comment by eaviles** [comment]
Hi @jachen-alch, thanks for reporting this. Any change you could describe a bit more your setup so we can replicate it? e.g. number of streams/shards/consumers. We will take a look at this.

**Comment by jachen-alch** [comment]
Thanks for the quick response on this @eaviles!

We had two different systems that were using lifion:
System 1:
10 clusters * 2 tasks/cluster * 2 processes/task * 4 consumers/process * 3 DescribeStream calls/min = 480 calls/min

System 2:
10 clusters * 2 tasks/cluster * 2 processes/task * 2 consumers/process * 3 DescribeStream calls/min = 240 calls/min

Total calls = 720/min

When we ran into this issue, we investigated the code and found system 2 only needed to write to streams not consume, so we shut off the consumers there. 5 of the 10 clusters in system 1 are also for testing, so we stopped those temporarily to see if it would solve the issue.

When we were seeing the issues, we were able to take spot measurements of these calls and saw we were making 796/min. After we shut down consumers from system 2 and half of system 1 we saw that number go down to 267/min, and no more rate limits from aws.

We found out about the 10 qps limit for `DescribeStream` from an aws support engineer while debugging this issue.

I don't think the specific setup is crucial, just the fact that we had 10*2*2*4 + 10*2*2*2 = 240 consumers going that were making 3 calls/min which put us over the 600 calls/min limit of `DescribeStream`.

Thanks,
James

**Comment by jachen-alch** [comment]
Additional info from aws support:

> Furthermore, you can consider using the APIs ListShards[1] and DescribeStreamSummary[2] together as the combination of these two APIs will give all the information given by the DescribeStream API. ListShards has a limit of 100 transactions per second per data stream. DescribeStreamSummary has a limit of 20 transactions per second per account.

**Comment by eaviles** [comment]
@jachen-alch please try lifion-kinesis@1.2.0, it will use DescribeStreamSummary now.
