### ISSUE TITLE
Supporting De-aggregation of Records

### ISSUE THREAD

**Issue by drshade** [lifion/lifion-kinesis#325]
I am using lifion-kinesis for consuming records which have been produced by FlinkKinesisProducer (which itself uses KPL) into a kinesis stream. 

By default the KPL is configured to aggregate messages before flushing (based on config property "AggregationEnabled" being set to true by default), and it seems like lifion-kinesis does not support de-aggregation of these messages.

As an example I am producing 4 simple string messages from my Flink application - each with the same PartitionKey of "WEBSOCKET":
```
{"id": "c2de27bd", "msg": "DISCONNECTED_ACK"}
{"id": "8003c0e2", "msg": "CONNECTED_ACK"}
{"id": "8003c0e2", "msg": "AUTHENTICATED_ACK"}
{"id": "8003c0e2", "msg": "SUBSCRIBED_ACK"}
```

And on the receiving side (lifion-kinesis) I receive the following:
```
{"id": "c2de27bd", "msg": "DISCONNECTED_ACK"}
{"id": "8003c0e2", "msg": "CONNECTED_ACK"}
��
        WEBSOCKET.{"id": "8003c0e2", "msg": "AUTHENTICATED_ACK"}+{"id": "8003c0e2", "msg": "SUBSCRIBED_ACK"}DUJ���R%Ѽ�_B�
```

(Yes the last one is garbled - obviously printing non-printables)

So I made use of the AWS CLI and pulled the records directly and I get the following:
```
{
    "Records": [
        {
            "SequenceNumber": "49606579326406038367464048750237457368417136686533705730",
            "ApproximateArrivalTimestamp": 1588670713.454,
            "Data": "eyJpZCI6ICJjMmRlMjdiZCIsICJtc2ciOiAiRElTQ09OTkVDVEVEX0FDSyJ9",
            "PartitionKey": "WEBSOCKET"
        },
        {
            "SequenceNumber": "49606579326406038367464048751263835389269956924578725890",
            "ApproximateArrivalTimestamp": 1588670714.062,
            "Data": "eyJpZCI6ICI4MDAzYzBlMiIsICJtc2ciOiAiQ09OTkVDVEVEX0FDSyJ9",
            "PartitionKey": "WEBSOCKET"
        },
        {
            "SequenceNumber": "49606579326406038367464048751789718120802320615575912450",
            "ApproximateArrivalTimestamp": 1588670714.376,
            "Data": "84mawgoJV0VCU09DS0VUGjIIABoueyJpZCI6ICI4MDAzYzBlMiIsICJtc2ciOiAiQVVUSEVOVElDQVRFRF9BQ0sifRovCAAaK3siaWQiOiAiODAwM2MwZTIiLCAibXNnIjogIlNVQlNDUklCRURfQUNLIn1EVUp/1g6VzFIl0bzcX0KU",
            "PartitionKey": "a"
        }
    ],
... }
```

As you can see the last 2 records have been aggregated by the KPL, and should be de-aggregated by the consumer.

Of course I can workaround this issue by setting "AggregationEnabled" to "false" - but I think this should be supported within lifion-kinesis.

I am very happy to fix this and submit a pull request if you agree on my assessment above - please let me know.

**Comment by jnickels** [comment]
Can I vote for this? This would be really appreciated.
@drshade Can you just create a PR so I can take a look at your solution?

**Comment by BizzlePop34** [comment]
@drshade I have a PR to add deaggregation options.  Please take a look. #388

**Comment by drshade** [comment]
LGTM @BizzlePop34 - thank you.
