### ISSUE TITLE
Need to be able to adjust ACQUIRE_LEASES_INTERVAL

### ISSUE THREAD

**Issue by duinness** [lifion/lifion-kinesis#342]
Related to #312, even with doubling the rate limit to 20/second by switching to describeStreamSummary (which helped tremendously) we are still occasionally hitting the aws rate limit for ReadProvisionedThroughputExceeded in our development aws account.

If we were able to adjust how often the lease acquisition attempts were made we could give ourselves extra headroom as we scale up our use even further.

**Comment by jennyEckstein** [comment]
@duinness We released lifion-kinesis@1.3.0 with your changes. Thank you for your contribution and your patience.

**Comment by duinness** [comment]
That's great news!
Thanks!
