### ISSUE TITLE
Writable Stream example does not work. 

### ISSUE THREAD

**Issue by mikedizon** [lifion/lifion-kinesis#429]
The example in the README does not work.

```
import Kinesis from 'lifion-kinesis';
import stream from 'stream';

stream.pipeline([
  new Kinesis({streamName:'streamName'}),
  new Writable({
    objectMode: true,
    write(data, encoding, callback) {
      console.log(data);
      callback();
    }
  })
]);
```

Running the code as-is returns this error ```Callback must be a function. Received Writable```

I have updated the code to promisify the pipeline function, which resolves the error, but no data is read from the stream.

```
import Kinesis from 'lifion-kinesis';
import stream from 'stream';
import util from 'util';

const pipeline = util.promisify(stream.pipeline);
pipeline([
  new Kinesis({streamName:'streamName'}),
  new Writable({
    objectMode: true,
    write(data, encoding, callback) {
      console.log(data);
      callback();
    }
  })
]);
```

**Comment by d-mon-** [comment]
Hi @mikedizon,

I managed to make it work on my side with the current implementation lifion/lifion-kinesis/pull/462. 
Hoping this will resolve your issue.
