### ISSUE TITLE
Support for a polling mode, using the GetRecords API

### ISSUE THREAD

**Issue by jhuiting** [lifion/lifion-kinesis#87]
First of all thanks for implementing this library, this looks like a much better option for using Kinesis in Node than the `AWS KCL` library! The stream-based design is a nice way to expose this to NodeJS clients.

 I'm currently investigating for which of our use cases we want to use the `Enhanced fan-out`, and for which ones we'd like to stick to the `v1` API. That of course depends on factors like latency requirements, amount of data send and costs. One of the other drawbacks for the `v2` API right now is that `Kinesalite` doesn't support running this locally yet, which makes it a lot harder to test and develop with the newer APIs. That could be a reason to still use `v1` API for some use cases. 

The README mentions that support for polling mode using GetRecords API is an `Incoming feature`, is there currently any work done on that? I can of course also put some time in to help out on this, and try to implement that feature. I'm curious if there are some initial ideas already on how to implement this.

**Comment by eaviles** [comment]
@jhuiting Hi Jos! it's been taking us longer than we expected but the support for polling by using the GetRecords API should be out shortly (at most 3 weeks from now). The implementation is based on our internal codebase and in lessons learned from running that code in production for months now so we are confident you will find this useful. Thanks a lot for your offer to help, we would appreciate it if you could give this module a try and maybe help us make it better so everybody can benefit from it? I'll make sure to let you know once we have a release.

**Comment by jhuiting** [comment]
@eaviles Great to hear it's in development. Will definitely give it a try once it's out, thanks for the update!

**Comment by jhuiting** [comment]
@eaviles Any updates on this?

**Comment by eaviles** [comment]
@jhuiting I don't know if you noticed it already but we just released the support for polling in addition to the enhanced fan-out consumers. Let us know how it goes!

**Comment by jhuiting** [comment]
@eaviles Thanks for the update! Will try it and provide some feedback.
