### ISSUE TITLE
Buffer issue running sample code

### ISSUE THREAD

**Issue by samueldelesque** [lifion/lifion-kinesis#91]
This library looks awesome, was trying to use it using the example but ran into some issues when actually receiving data. See the output below, it's successfully connecting and fetching data, but an event with actual data comes it it fails.

```Trying to connect the client…
Checking if the stream "loadtest_notifications_consumer" exists…
The stream status is ACTIVE.
Checking if the "consumer-name" consumer for "loadtest_notifications_consumer" exists…
The stream consumer exists already and is active.
Retrieving the shards for the stream "loadtest_notifications_consumer"…
Creating subscribers for the stream shards using "consumer-name"…
Starting a "consumer-name" subscriber for shard "shardId-000000000000"…
Starting position: LATEST
Starting a "consumer-name" subscriber for shard "shardId-000000000001"…
Starting position: LATEST
The client is now connected.
Subscription to shard is successful.
Event "initial-response" emitted.
Subscription to shard is successful.
Event "initial-response" emitted.
Incoming data: { continuationSequenceNumber: '49593840296553928185147946290399650652941424392134459410',
  millisBehindLatest: 0,
  records: [],
  shardId: 'shardId-000000000001' }
Pipeline closed with error: Error: Expected 22315 bytes in the buffer but got 16341.
    at parse (/node_modules/lifion-aws-event-stream/lib/index.js:54:11)
    at Parser._transform (/node_modules/lifion-aws-event-stream/lib/index.js:203:17)
    at Parser.Transform._read (_stream_transform.js:190:10)
    at Parser.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Parser.Writable.write (_stream_writable.js:294:11)
    at Transform.ondata (_stream_readable.js:689:20)
    at Transform.emit (events.js:189:13)
    at Transform.EventEmitter.emit (domain.js:441:20)
```

Here's the code I am running:
```
const Kinesis = require('lifion-kinesis');
const config = require('../config');
const streamName = 'loadtest_notifications_consumer';
const consumerName = 'consumer-name';
const client = new Kinesis({
    streamName,
    consumerName,
    region: config.AWS_DEFAULT_REGION,
    logger: console
});
client.on('data', (chunk) => {
    console.log('Incoming data:', chunk);
});
client.on('error', (error) => {
    console.log('Error:', error);
});

client.connect();
```

Thanks for any help!

**Comment by eaviles** [comment]
Hi @samueldelesque thanks for reporting this. The error you are getting is due to missing bytes in a chunk. The module right now expects the entire message in a single chuck of data I wonder if the message you are trying to receive is getting split into multiple chunks. Could you put one of the messages here? Thanks!

**Comment by samueldelesque** [comment]
Hey @eaviles - thanks for getting back to me. The messages are json objects compressed using Snappy, but I am failing to understand why they would be chunked differently.

**Comment by eaviles** [comment]
@samueldelesque What about the size of the messages? (e.g. 1 KB, 2 KB, etc)

**Comment by samueldelesque** [comment]
3kb

**Comment by eaviles** [comment]
@samueldelesque we were able to replicate the issue and we made sure to release the fix as part of a major feature release. Please note that we had to change the `connect` call to `startConsumer` (long story there). Let me know if the latest version of this module works for you!

**Comment by eaviles** [comment]
@samueldelesque I'm closing this issue as we were able to replicate the problem and the fix was released. Let us know if you are still having issues and we will reopen this.

**Comment by samueldelesque** [comment]
That's great thank you @eaviles !
